from pathlib import Path
import re

from fpdf import FPDF


OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def safe_text(value) -> str:
    """Convert text into safe PDF-compatible text."""
    if value is None:
        return ""

    text = str(value)

    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2026": "...",
        "\u00a0": " ",
        "\u2011": "-",
        "\u2022": "-",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    # Remove problematic control characters
    text = re.sub(r"[\x00-\x08\x0B\x0C\x0E-\x1F]", "", text)

    # Break extremely long words/tokens so FPDF can wrap them
    text = re.sub(r"(\S{45})(?=\S)", r"\1 ", text)

    return text.strip()


def add_text(pdf: FPDF, label: str, value: str):
    """Safely add a labelled text section."""
    value = safe_text(value)

    if not value:
        return

    pdf.set_font("Helvetica", "B", 11)
    pdf.multi_cell(
        0,
        7,
        safe_text(label),
        new_x="LMARGIN",
        new_y="NEXT",
    )

    pdf.set_font("Helvetica", "", 10)

    pdf.multi_cell(
        0,
        6,
        value,
        new_x="LMARGIN",
        new_y="NEXT",
    )

    pdf.ln(2)


def save_pdf(layout: list[dict]) -> str:
    """
    Create a PDF comic from the layout generated by build_comic_layout().
    """

    pdf = FPDF(
        orientation="P",
        unit="mm",
        format="A4",
    )

    pdf.set_auto_page_break(
        auto=True,
        margin=15,
    )

    for panel in layout:

        pdf.add_page()

        # -----------------------------
        # PANEL TITLE
        # -----------------------------

        pdf.set_font("Helvetica", "B", 18)

        title = safe_text(
            f"Panel {panel.get('panel_number', '')}: "
            f"{panel.get('title', '')}"
        )

        pdf.multi_cell(
            0,
            10,
            title,
            align="C",
            new_x="LMARGIN",
            new_y="NEXT",
        )

        pdf.ln(4)

        # -----------------------------
        # IMAGE
        # -----------------------------

        image_path = panel.get("image_path")

        if image_path:
            image_file = Path(str(image_path))

            if image_file.exists() and image_file.is_file():

                try:
                    pdf.image(
                        str(image_file),
                        x=20,
                        y=None,
                        w=170,
                    )

                    pdf.ln(5)

                except Exception as image_error:
                    pdf.set_font("Helvetica", "", 9)
                    pdf.multi_cell(
                        0,
                        6,
                        safe_text(
                            f"Image could not be displayed: {image_error}"
                        ),
                        new_x="LMARGIN",
                        new_y="NEXT",
                    )

        # -----------------------------
        # CAPTION
        # -----------------------------

        add_text(
            pdf,
            "Caption",
            panel.get("caption", ""),
        )

        # -----------------------------
        # NARRATION
        # -----------------------------

        add_text(
            pdf,
            "Narration",
            panel.get("narration", ""),
        )

        # -----------------------------
        # DIALOGUE
        # -----------------------------

        add_text(
            pdf,
            "Dialogue",
            panel.get("dialogue", ""),
        )

        # -----------------------------
        # SCENE DESCRIPTION
        # -----------------------------

        add_text(
            pdf,
            "Scene",
            panel.get("scene_description", ""),
        )

    output_file = OUTPUT_DIR / "comiccraft_comic.pdf"

    pdf.output(str(output_file))

    return str(output_file)